import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useAccount, useConnect, usePublicClient } from 'wagmi';
import { useIsMounted } from '../hooks/useIsMounted';
import {ethers, EtherscanProvider } from 'ethers'

const Home: NextPage = () => {

  const { isMounted } = useIsMounted();
  const { address, isConnected, connector: activeConnector } = useAccount();
  const { connect, connectors, error, isLoading, pendingConnector } = useConnect();
  const provider = usePublicClient();

  
  
  async function fetchContractGreeting() {
    if(provider) {  
      console.log(provider);
      // const contract = new ethers.Contract()
      // try {

      // }
    } else {
      {
        console.log('is not exist provider');
        
      }
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        {isMounted && address && (
            <div>
              <p>{address}</p>
              <button onClick={fetchContractGreeting}>{address ? 'Fetch Greeting' : 'Please Connect Your Wallet'}</button>
            </div>
          )
        }
        {isMounted && isConnected && <div>Connected to {activeConnector?.name}</div>}
      </main>

    
    </div>
  );
};

export default Home;
